# frozen_string_literal: true

source 'https://rubygems.org'

gem 'minitest'
gem 'nokogiri'
gem 'nori'
gem 'rack'
gem 'rack-parser', require: 'rack/parser'
gem 'rack-test', require: 'rack/test'
gem 'rackup'
gem 'rake'
gem 'sinatra'

group :development, :test do
  # Audits gems for known security defects (use config/bundler-audit.yml to ignore issues)
  gem 'bundler-audit', require: false

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', require: false

  gem 'fasterer'
  gem 'reek'
  gem 'rubocop'
end
