# A sample Gemfile
source "https://rubygems.org"

gem "rake"
gem "sinatra"
gem "minitest"
gem "rack"
gem "rack-test", require: "rack/test"
gem "rack-parser", require: "rack/parser"
gem "nori"
gem "nokogiri"
gem "rackup", "~> 2.1"
