sudo: false
language: csharp 
dist: trusty
dotnet: 2.1.301
install:
  # workaround for missing .net 4.5 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
script: 
  - cd ./clean-aspnet-core/ && ./build.sh && cd ..
  - cd ./suave/ && ./build.sh test && cd ..
  - cd ./clean-aspnet-core-fsharp/ && ./build.sh test && cd ..
  - cd ./nancy/ && ./build.sh && cd ..
  - cd ./node/ && npm install && npm run test && cd ..
  - cd ./aspnet-mvc/ && ./build.sh test && cd ..
branches:
  only: 
    - master
