sudo: false
language: csharp 
dist: trusty
dotnet: 2.1.105
script: 
  - cd ./clean-aspnet-core/ && ./build.sh && cd ..
  - cd ./owin/ && ./build.sh && cd ..
  - cd ./suave/ && ./build.sh test && cd ..
  - cd ./owin_fsharp/ && ./build.sh test && cd ..

branches:
  only: 
    - master
