image: Visual Studio 2017
version: 1.0.{build}
environment:
  nodejs_version: "8"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - cmd: cd .\node\ && npm install && cd ..
configuration: Release
build_script:
  - cmd: cd .\clean-aspnet-core\ && .\build.cmd && cd ..
  - cmd: cd .\owin\ && .\build.cmd && cd ..
  - cmd: cd .\suave\ && .\build.cmd test && cd ..
  - cmd: cd .\clean-aspnet-core-fsharp\ && .\build.cmd test && cd ..
  - cmd: cd .\nancy\ && .\build.cmd && cd ..
  - cmd: cd .\node\ && npm run test && cd ..

test: off
nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
branches:
  only:
  - master
