/*
 * Customer Service
 *
 * Port of the api for demonstrating mvvm found at [galasoft](https://galasoft.ch/labs/Customers/CustomerService.svc).
 *
 * API version: 1.0.0-oas3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package customerservice

type Customer struct {
	AccountNumber int32 `json:"accountNumber,omitempty"`

	AddressCity string `json:"addressCity,omitempty"`

	AddressCountry string `json:"addressCountry,omitempty"`

	AddressStreet string `json:"addressStreet,omitempty"`

	FirstName string `json:"firstName,omitempty"`

	Gender string `json:"gender,omitempty"`

	LastName string `json:"lastName,omitempty"`

	PictureUri string `json:"pictureUri,omitempty"`
}
