openapi: 3.0.0
info:
  title: Customer Service
  description: "Port of the api for demonstrating mvvm found at [galasoft](https://galasoft.ch/labs/Customers/CustomerService.svc)."
  version: 1.0.0-oas3
servers:
- url: /
paths:
  /CustomerService.svc/GetAllCustomers:
    get:
      tags:
      - CustomerService
      operationId: Get
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfCustomer'
            text/xml:
              schema:
                $ref: '#/components/schemas/ArrayOfCustomer'
  /CustomerService.svc/SaveCustomer:
    post:
      tags:
      - CustomerService
      operationId: Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
          application/xml:
            schema:
              $ref: '#/components/schemas/Customer'
          text/xml:
            schema:
              $ref: '#/components/schemas/Customer'
          application/*+xml:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        "200":
          description: Success
          content:
            application/xml:
              schema:
                type: boolean
                x-content-type: application/xml
            text/xml:
              schema:
                type: boolean
components:
  schemas:
    ArrayOfCustomer:
      type: object
      properties:
        customer:
          uniqueItems: false
          type: array
          items:
            $ref: '#/components/schemas/Customer'
      example:
        customer:
        - addressCountry: addressCountry
          firstName: firstName
          lastName: lastName
          gender: Male
          addressStreet: addressStreet
          pictureUri: pictureUri
          accountNumber: 0
          addressCity: addressCity
        - addressCountry: addressCountry
          firstName: firstName
          lastName: lastName
          gender: Male
          addressStreet: addressStreet
          pictureUri: pictureUri
          accountNumber: 0
          addressCity: addressCity
    Customer:
      type: object
      properties:
        accountNumber:
          type: integer
          format: int32
        addressCity:
          type: string
        addressCountry:
          type: string
        addressStreet:
          type: string
        firstName:
          type: string
        gender:
          type: string
          format: string
          enum:
          - Male
          - Female
          - Boy
          - Girl
        lastName:
          type: string
        pictureUri:
          $ref: '#/components/schemas/XmlUri'
      example:
        addressCountry: addressCountry
        firstName: firstName
        lastName: lastName
        gender: Male
        addressStreet: addressStreet
        pictureUri: pictureUri
        accountNumber: 0
        addressCity: addressCity
    XmlUri:
      type: string
