name: Clojure 

on: 
  push:
    paths:
      - 'clojure/**'
  pull_request:
    paths:
      - 'clojure/**'

env:
  FILE_PATH: clojure 

jobs:

  clojure:

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          # Install just one or all simultaneously
          cli: 1.10.3.855 # Clojure CLI based on tools.deps
          lein: 2.9.6     # or use 'latest' to always provision latest version of leiningen

      - name: Execute clojure code on Linux and MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: ${{env.FILE_PATH}}
        run: lein test
        shell: bash

      - name: Execute clojure code on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ${{env.FILE_PATH}}
        run: lein test
        shell: powershell
        
      - name: Get leiningen version
        working-directory: ${{env.FILE_PATH}}
        run: lein -v
        