name: Ruby Sinatra

env:
  # Path to the solution file relative to the root of the project.
  FILE_PATH: sinatra
  
on:
  push:
    paths:
      - 'sinatra/**'
  pull_request:
    paths:
      - 'sinatra/**'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: ${{env.FILE_PATH}}
    - name: Run tests
      working-directory: ${{env.FILE_PATH}}
      run: bundle exec rake test
